enum BlendMethod { HSL = 0, RGB };

enum EffectSetting { NORMAL = 0, SINGLECOLOUR, TWOCOLOUR , RANDOMSINGLECOLOUR};

enum Palette { ALL = 0, COMPLEMENTARY, MONOCHROMATIC, ANALOGOUS, SPLITCOMPLEMENTS, TRIADIC, TETRADIC, MULTI}; 

enum Colour { RANDOM_COLOUR = 0, SPECIFIC_COLOUR }; 